### ISSUE TITLE
Use admin account as payer on all outgoing transactions

### ISSUE THREAD

**Issue by tehranifar** [onflow/wallet-api#11]
We expect the admin account to contain enough FLOW to compensate for all custodial accounts' transactions. 

Some endpoints (like FT withdrawal) use the user account as the payer, thus running into problems when transactions fail and the storage falls below the minimum. 

All outgoing transactions from wallet-api should use the admin account as payer.

**Comment by uhbif19** [comment]
@tehranifar

It looks to me that all transactions send by hand are paid by user. Flow are taken from account after each transaction. Am I correct?

**Comment by tehranifar** [comment]
Yes, designating the admin account as `payer` will automatically make it pay for user transactions.

**Comment by uhbif19** [comment]
@uhbif19 I am not sure what you mean. 'designating the admin account as payer' - is that something possible in Wallet API? Or your answer is about situation when working with a regular Flow client libruary?

**Comment by psiemens** [comment]
Hey @tehranifar, I've moved this issue to the new upstream repository here: https://github.com/flow-hydraulics/flow-wallet-api/issues/152
