### ISSUE TITLE
Only String argument types is working when sending transaction through through the wallet

### ISSUE THREAD

**Issue by m4nuC** [onflow/wallet-api#15]
When sending a transaction it seems that only the string type is currently working.

ie.: this will work
```
{
  "code":"transaction(greeting: String) { execute { log(greeting.concat(\", World!\")) }}",
  "arguments":[{"type":"String","value":"Hello"}]
}
```

But this won't
```
{
  "code":"transaction(greeting: UInt64) { execute { log(greeting.concat(\", World!\")) }}",
  "arguments":[{"type":"UInt64","value":"Hello"}]
}

```
Error is: 

`Error while processing job: failed to decode value: invalid JSON Cadence structure`

**Comment by psiemens** [comment]
Hey @m4nuC, I migrated this issue to the new upstream repository here: https://github.com/flow-hydraulics/flow-wallet-api/issues/153
