### ISSUE TITLE
KMS Signer not working for admin account

### ISSUE THREAD

**Issue by davidhouseholter-hah** [onflow/wallet-api#16]
I created a new key in my KMS and converted the PEM to Hex and then created an account on the testnet. When I configure the wallet-api to use this address on the testnet I get the following error: 

invalid proposal key: public key 0 on account 0xxxxx  does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account 0xxxxx does not have a valid signature: signature is not valid  
exit status 1

**Comment by psiemens** [comment]
Thanks for opening this @davidhouseholter-hah! Great to chat in office hours :) 

We're in the middle of a repository migration, so I moved this issue to the new upstream repository here: https://github.com/flow-hydraulics/flow-wallet-api/issues/154
