### ISSUE TITLE
Implement AMPQ Message client for Job updates

### ISSUE THREAD

**Issue by davidhouseholter-incoperate** [onflow/wallet-api#17]
I added a new package to publish messages to a message queue. I still need to add the event bus name to the cfg file but I thought it was best to talk to members of the team about architecture. I would like this logic to use the JobService but currently, the service is not being used for creating or update.

The changes I have made currently: https://github.com/onflow/wallet-api/compare/main...davidhouseholter-hah:ampq_message_client?expand=1

**Comment by psiemens** [comment]
This is great, @davidhouseholter-hah.

I've moved the issue to the new upstream repository here: https://github.com/flow-hydraulics/flow-wallet-api/issues/155

Let's discuss there!
