### ISSUE TITLE
Expose API port via a environment variable

### ISSUE THREAD

**Issue by m4nuC** [onflow/wallet-api#9]
Currently, it seems to pick up the default PORT variable which is not ideal in a multi-service environment

**Comment by psiemens** [comment]
@m4nuC Would it help to have a prefix on the environment variable? e.g. `FLOW_PORT`

**Comment by m4nuC** [comment]
@psiemens yes definitely. Maybe even `FLOW_WALLET_PORT` or `FLOW_WALLET_API_PORT`?

**Comment by psiemens** [comment]
Thanks for reporting this! I've moved it to the new upstream repository here: https://github.com/flow-hydraulics/flow-wallet-api/issues/151
